# Generated by Django 4.2.20 on 2025-07-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_profile_description_profile_xx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="xx",
            new_name="description",
        ),
    ]
